<a href="https://colab.research.google.com/github/22yuu/Colab/blob/main/2_Numpy_%EC%8B%A4%EC%8A%B5%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
날짜 : 2021/07/05
이름 : 이진유
내용 : 파이썬 Numpy 패키지 실습하기
"""

import numpy as np

In [ ]:
#Numpy 자료구조 - 벡터
v1 = np.array([1, 2, 3, 4, 5])
v1
print('v1 : ', v1)

v2 = np.arange(5)
print('v2 : ', v2)

v3 = np.arange(10)
print('v3 : ', v3)

v1 :  [1 2 3 4 5]
v2 :  [0 1 2 3 4]
v3 :  [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 0 ~ 1 사이의 임의의 실수
rand1 = np.random.rand(100)
print(rand1)

# 표준 정규분포를 따르는 실수 100개
rand2 = np.random.randn(100)
print(rand2)

# 0 - 9 사이의 임의의 정수
rand3 = np.random.randint(10)
print(rand3)

[0.90289857 0.66924798 0.15191424 0.01262603 0.88981675 0.60607861
 0.4010815  0.23455573 0.5132389  0.71346227 0.48986218 0.02047637
 0.04478925 0.43502638 0.39666036 0.68181771 0.31773412 0.07524765
 0.18787981 0.73262451 0.68872525 0.79201805 0.88739485 0.41964614
 0.84987923 0.19183872 0.46036134 0.74654837 0.48575324 0.40771081
 0.27196082 0.22015291 0.20016114 0.74192132 0.97440081 0.81970866
 0.74410928 0.06097326 0.42330755 0.77814714 0.31824068 0.72610065
 0.29419796 0.17162745 0.91084124 0.76251362 0.55492055 0.83971934
 0.64847896 0.99857551 0.40640586 0.32945911 0.86963488 0.85704689
 0.45319872 0.35040593 0.39411931 0.65001709 0.05910235 0.78211635
 0.99249    0.21195016 0.02263318 0.47837873 0.63262944 0.19145355
 0.60213149 0.59168675 0.39913863 0.5761037  0.56631492 0.70772688
 0.92433425 0.57742054 0.98091316 0.56848327 0.55655292 0.47156428
 0.20937932 0.28036547 0.99585423 0.17249852 0.20645767 0.20930739
 0.21639613 0.83039566 0.45374544 0.11360803 0.80883744 0.5197

In [ ]:
# Numpy 자료구조 - 행렬
m1 = np.array([[1,2],[3,4]])
print(m1)

m2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(m2)

m3 = np.ones([2,4])
print(m3)

m4 = np.zeros([3,2])
print(m4)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# 전치행렬
print(m1)
print(m1.T)
print(m2)
print(m2.transpose())
print(m2.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
# 단위행렬
e1 = np.identity(2)
print(e1)

e2 = np.identity(3)
print(e2)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 역행렬
im1 = np.linalg.inv(m1)
print(im1)

print(m1 * im1)
result = m1.dot(im1)
print(result.round())

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# 행렬 인덱싱
matrix = np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
print(matrix)

print(matrix[0, 0])
print(matrix[0, :])
print(matrix[:, 0])

print(matrix[0:2, 0:2])
print(matrix[:, 0:2])
print(matrix[:, 2:4])
print(matrix[1:3, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[1 2 3 4]
[1 5 9]
[[1 2]
 [5 6]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
